# Generated by Django 4.2.7 on 2023-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.CharField(default='', max_length=500)),
                ('page_cover', models.ImageField(blank=True, upload_to='page-covers/')),
                ('song_cover', models.ImageField(blank=True, upload_to='song-covers/')),
                ('notes', models.ImageField(blank=True, upload_to='notes')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('section', models.ManyToManyField(to='main.section')),
            ],
        ),
    ]
