# Generated by Django 4.2.7 on 2023-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
