# Generated by Django 3.2.6 on 2023-11-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_song_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
