# Generated by Django 3.2.6 on 2023-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='section',
        ),
        migrations.AddField(
            model_name='song',
            name='section',
            field=models.CharField(choices=[('btf', 'Красиво'), ('fun', 'Весело'), ('sad', 'Грустно')], default=[('btf', 'Красиво'), ('fun', 'Весело'), ('sad', 'Грустно')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
