# Generated by Django 3.2.6 on 2023-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231203_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='icon',
            field=models.ImageField(blank=True, upload_to='playlist-icon/'),
        ),
    ]
