# Generated by Django 3.2.6 on 2023-12-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_playlist_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='type',
            new_name='section',
        ),
    ]
