# Generated by Django 3.2.6 on 2023-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='section',
            field=models.CharField(choices=[('bea', 'Красивое'), ('fun', 'Весело'), ('sad', 'Грустно')], default='fun', max_length=3),
        ),
    ]
