# Generated by Django 3.2.6 on 2023-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_song_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
